/*

 dct36_3dnow.s - 3DNow! optimized dct36()

 This code based 'dct36_3dnow.s' by Syuuhei Kashiyama
 <squash@mb.kcom.ne.jp>,only two types of changes have been made:

 - remove PREFETCH instruction for speedup
 - change function name for support 3DNow! automatic detect

 You can find Kashiyama's original 3dnow! support patch
 (for mpg123-0.59o) at
 http://user.ecc.u-tokyo.ac.jp/~g810370/linux-simd/ (Japanese).

 by KIMURA Takuhiro <kim@hannah.ipc.miyakyo-u.ac.jp> - until 31.Mar.1999
                    <kim@comtec.co.jp>               - after  1.Apr.1999


 Replacement of dct36() with AMD's 3DNow! SIMD operations support

 Syuuhei Kashiyama <squash@mb.kcom.ne.jp>

 The author of this program disclaim whole expressed or implied
 warranties with regard to this program, and in no event shall the
 author of this program liable to whatever resulted from the use of
 this program. Use it at your own risk.
 
 Inline asm by Nickols_K <nickols_k@mail.ru>
*/
#include <mm3dnow.h>
#include "../../mplayerxp/pvector/mmx2c.h"
#include "mpg123.h"
#include "../../mplayerxp/mangle.h"
#include "../../mplayerxp/cpudetect.h"
extern real COS9[9];
extern real tfcos36[9];
static const real f1 = 1.0;

#define MK_PTR(base,off) ((void const *)(((char const *)base)+off))

void dct36_3dnow(real *_eax,real *_esi,real *_ecx,real *_edx,real *_ebx)
{
    __m64 mm[8];

    mm[0]=_m_load(&(((char *)_eax)[0]));
    mm[1]=_m_load(&(((char *)_eax)[4]));
    mm[0]=_m_pfadd(mm[0],mm[1]);
    _m_store(&(((char *)_eax)[4]),mm[0]);
    mm[1]=_m_psrlqi(mm[1],32);
    mm[2]=_m_load(&(((char *)_eax)[12]));
    mm[1]=_m_punpckldq(mm[1],mm[2]);
    mm[1]=_m_pfadd(mm[1],mm[2]);
    _m_store(&(((char *)_eax)[12]),mm[1]);
    mm[2]=_m_psrlqi(mm[2],32);
    mm[3]=_m_load(&(((char *)_eax)[20]));
    mm[2]=_m_punpckldq(mm[2],mm[3]);
    mm[2]=_m_pfadd(mm[2],mm[3]);
    _m_store(&(((char *)_eax)[20]),mm[2]);
    mm[3]=_m_psrlqi(mm[3],32);
    mm[4]=_m_load(&(((char *)_eax)[28]));
    mm[3]=_m_punpckldq(mm[3],mm[4]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    _m_store(&(((char *)_eax)[28]),mm[3]);
    mm[4]=_m_psrlqi(mm[4],32);
    mm[5]=_m_load(&(((char *)_eax)[36]));
    mm[4]=_m_punpckldq(mm[4],mm[5]);
    mm[4]=_m_pfadd(mm[4],mm[5]);
    _m_store(&(((char *)_eax)[36]),mm[4]);
    mm[5]=_m_psrlqi(mm[5],32);
    mm[6]=_m_load(&(((char *)_eax)[44]));
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store(&(((char *)_eax)[44]),mm[5]);
    mm[6]=_m_psrlqi(mm[6],32);
    mm[7]=_m_load(&(((char *)_eax)[52]));
    mm[6]=_m_punpckldq(mm[6],mm[7]);
    mm[6]=_m_pfadd(mm[6],mm[7]);
    _m_store(&(((char *)_eax)[52]),mm[6]);
    mm[7]=_m_psrlqi(mm[7],32);
    mm[0]=_m_load(&(((char *)_eax)[60]));
    mm[7]=_m_punpckldq(mm[7],mm[0]);
    mm[7]=_m_pfadd(mm[7],mm[0]);
    _m_store(&(((char *)_eax)[60]),mm[7]);
    mm[0]=_m_psrlqi(mm[0],32);
    mm[1]=_m_load_half(&(((char *)_eax)[68]));
    mm[0]=_m_pfadd(mm[0],mm[1]);
    _m_store_half(&(((char *)_eax)[68]),mm[0]);
    mm[0]=_m_load_half(&(((char *)_eax)[4]));
    mm[1]=_m_load_half(&(((char *)_eax)[12]));
    mm[0]=_m_punpckldq(mm[0],mm[1]);
    mm[1]=_m_punpckldq(mm[1],_m_load(&(((char *)_eax)[20])));
    mm[0]=_m_pfadd(mm[0],mm[1]);
    _m_store_half(&(((char *)_eax)[12]),mm[0]);
    mm[0]=_m_psrlqi(mm[0],32);
    _m_store_half(&(((char *)_eax)[20]),mm[0]);
    mm[1]=_m_psrlqi(mm[1],32);
    mm[2]=_m_load_half(&(((char *)_eax)[28]));
    mm[1]=_m_punpckldq(mm[1],mm[2]);
    mm[2]=_m_punpckldq(mm[2],_m_load(&(((char *)_eax)[36])));
    mm[1]=_m_pfadd(mm[1],mm[2]);
    _m_store_half(&(((char *)_eax)[28]),mm[1]);
    mm[1]=_m_psrlqi(mm[1],32);
    _m_store_half(&(((char *)_eax)[36]),mm[1]);
    mm[2]=_m_psrlqi(mm[2],32);
    mm[3]=_m_load_half(&(((char *)_eax)[44]));
    mm[2]=_m_punpckldq(mm[2],mm[3]);
    mm[3]=_m_punpckldq(mm[3],_m_load(&(((char *)_eax)[52])));
    mm[2]=_m_pfadd(mm[2],mm[3]);
    _m_store_half(&(((char *)_eax)[44]),mm[2]);
    mm[2]=_m_psrlqi(mm[2],32);
    _m_store_half(&(((char *)_eax)[52]),mm[2]);
    mm[3]=_m_psrlqi(mm[3],32);
    mm[4]=_m_load_half(&(((char *)_eax)[60]));
    mm[3]=_m_punpckldq(mm[3],mm[4]);
    mm[4]=_m_punpckldq(mm[4],_m_load(&(((char *)_eax)[68])));
    mm[3]=_m_pfadd(mm[3],mm[4]);
    _m_store_half(&(((char *)_eax)[60]),mm[3]);
    mm[3]=_m_psrlqi(mm[3],32);
    _m_store_half(&(((char *)_eax)[68]),mm[3]);
    mm[0]=_m_load(&(((char *)_eax)[24]));
    mm[1]=_m_load(&(((char *)_eax)[48]));
    mm[2]=_m_load_half(MK_PTR(COS9,12));
    mm[2]=_m_punpckldq(mm[2],mm[2]);
    mm[3]=_m_load_half(MK_PTR(COS9,24));
    mm[3]=_m_punpckldq(mm[3],mm[3]);
    mm[0]=_m_pfmul(mm[0],mm[2]);
    mm[1]=_m_pfmul(mm[1],mm[3]);
    mm[7]=_m_load_half(&f1);
    mm[2]=_m_load(&(((char *)_eax)[8]));
    mm[3]=_m_load_half(MK_PTR(COS9,4));
    mm[3]=_m_punpckldq(mm[3],mm[3]);
    mm[2]=_m_pfmul(mm[2],mm[3]);
    mm[2]=_m_pfadd(mm[2],mm[0]);
    mm[3]=_m_load(&(((char *)_eax)[40]));
    mm[4]=_m_load_half(MK_PTR(COS9,20));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfadd(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[56]));
    mm[4]=_m_load_half(MK_PTR(COS9,28));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfadd(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[0]));
    mm[4]=_m_load(&(((char *)_eax)[16]));
    mm[5]=_m_load_half(MK_PTR(COS9,8));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[32]));
    mm[5]=_m_load_half(MK_PTR(COS9,16));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[3]=_m_pfadd(mm[3],mm[1]);
    mm[4]=_m_load(&(((char *)_eax)[64]));
    mm[5]=_m_load_half(MK_PTR(COS9,32));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[4]=mm[2];
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,0)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[108]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[104])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[5]=_m_pswapd(mm[5]);
    _m_store(&(((char *)_ecx)[32]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[32]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[36])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[32]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[36])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[1024]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1152]),mm[5]);
    mm[4]=mm[3];
    mm[4]=_m_pfsub(mm[4],mm[2]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,32)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[140]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[72])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[68]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[0]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[0]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[68])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[0]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[68])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[0]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[2176]),mm[5]);
    mm[2]=_m_load(&(((char *)_eax)[8]));
    mm[3]=_m_load(&(((char *)_eax)[40]));
    mm[2]=_m_pfsub(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[56]));
    mm[2]=_m_pfsub(mm[2],mm[3]);
    mm[3]=_m_load_half(MK_PTR(COS9,12));
    mm[3]=_m_punpckldq(mm[3],mm[3]);
    mm[2]=_m_pfmul(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[16]));
    mm[4]=_m_load(&(((char *)_eax)[32]));
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[64]));
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=_m_load_half(MK_PTR(COS9,24));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[48]));
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[0]));
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[4]=mm[2];
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,4)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[112]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[100])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[40]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[28]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[28]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[40])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[28]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[40])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[896]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1280]),mm[5]);
    mm[4]=mm[3];
    mm[4]=_m_pfsub(mm[4],mm[2]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,28)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[136]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[76])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[64]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[4]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[4]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[64])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[4]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[64])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[128]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[2048]),mm[5]);
    mm[2]=_m_load(&(((char *)_eax)[8]));
    mm[3]=_m_load_half(MK_PTR(COS9,20));
    mm[3]=_m_punpckldq(mm[3],mm[3]);
    mm[2]=_m_pfmul(mm[2],mm[3]);
    mm[2]=_m_pfsub(mm[2],mm[0]);
    mm[3]=_m_load(&(((char *)_eax)[40]));
    mm[4]=_m_load_half(MK_PTR(COS9,28));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfsub(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[56]));
    mm[4]=_m_load_half(MK_PTR(COS9,4));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfadd(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[0]));
    mm[4]=_m_load(&(((char *)_eax)[16]));
    mm[5]=_m_load_half(MK_PTR(COS9,32));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[32]));
    mm[5]=_m_load_half(MK_PTR(COS9,8));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[3]=_m_pfadd(mm[3],mm[1]);
    mm[4]=_m_load(&(((char *)_eax)[64]));
    mm[5]=_m_load_half(MK_PTR(COS9,16));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[4]=mm[2];
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,8)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[116]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[96])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[44]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[24]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[24]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[44])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[24]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[44])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[768]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1408]),mm[5]);
    mm[4]=mm[3];
    mm[4]=_m_pfsub(mm[4],mm[2]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,24)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[132]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[80])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[60]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[8]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[8]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[60])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[8]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[60])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[256]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1920]),mm[5]);
    mm[2]=_m_load(&(((char *)_eax)[8]));
    mm[3]=_m_load_half(MK_PTR(COS9,28));
    mm[3]=_m_punpckldq(mm[3],mm[3]);
    mm[2]=_m_pfmul(mm[2],mm[3]);
    mm[2]=_m_pfsub(mm[2],mm[0]);
    mm[3]=_m_load(&(((char *)_eax)[40]));
    mm[4]=_m_load_half(MK_PTR(COS9,4));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfadd(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[56]));
    mm[4]=_m_load_half(MK_PTR(COS9,20));
    mm[4]=_m_punpckldq(mm[4],mm[4]);
    mm[3]=_m_pfmul(mm[3],mm[4]);
    mm[2]=_m_pfsub(mm[2],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[0]));
    mm[4]=_m_load(&(((char *)_eax)[16]));
    mm[5]=_m_load_half(MK_PTR(COS9,16));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=_m_load(&(((char *)_eax)[32]));
    mm[5]=_m_load_half(MK_PTR(COS9,32));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfadd(mm[3],mm[4]);
    mm[3]=_m_pfadd(mm[3],mm[1]);
    mm[4]=_m_load(&(((char *)_eax)[64]));
    mm[5]=_m_load_half(MK_PTR(COS9,8));
    mm[5]=_m_punpckldq(mm[5],mm[5]);
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[3]=_m_pfsub(mm[3],mm[4]);
    mm[4]=mm[2];
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,12)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[120]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[92])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[48]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[20]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[20]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[48])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[20]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[48])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[640]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1536]),mm[5]);
    mm[4]=mm[3];
    mm[4]=_m_pfsub(mm[4],mm[2]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,20)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[128]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[84])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[56]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[12]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[12]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[56])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[12]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[56])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[384]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1792]),mm[5]);
    mm[4]=_m_load(&(((char *)_eax)[0]));
    mm[3]=_m_load(&(((char *)_eax)[16]));
    mm[4]=_m_pfsub(mm[4],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[32]));
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[48]));
    mm[4]=_m_pfsub(mm[4],mm[3]);
    mm[3]=_m_load(&(((char *)_eax)[64]));
    mm[4]=_m_pfadd(mm[4],mm[3]);
    mm[5]=mm[7];
    mm[5]=_m_punpckldq(mm[5],_m_load(MK_PTR(tfcos36,16)));
    mm[4]=_m_pfmul(mm[4],mm[5]);
    mm[5]=mm[4];
    mm[5]=_m_pfacc(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[124]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[88])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    _m_store_half(&(((char *)_ecx)[52]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ecx)[16]),mm[5]);
    mm[6]=mm[4];
    mm[5]=_m_punpckldq(mm[5],mm[6]);
    mm[5]=_m_pfsub(mm[5],mm[6]);
    mm[5]=_m_punpckhdq(mm[5],mm[5]);
    mm[6]=_m_load_half(&(((char *)_edx)[16]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_edx)[52])));
    mm[5]=_m_pfmul(mm[5],mm[6]);
    mm[6]=_m_load_half(&(((char *)_esi)[16]));
    mm[6]=_m_punpckldq(mm[6],_m_load(&(((char *)_esi)[52])));
    mm[5]=_m_pfadd(mm[5],mm[6]);
    _m_store_half(&(((char *)_ebx)[512]),mm[5]);
    mm[5]=_m_psrlqi(mm[5],32);
    _m_store_half(&(((char *)_ebx)[1664]),mm[5]);
    _m_femms();
}
