#!/bin/bash

unicode="--unicode"
font=./EuroStyle.ttf
#font=/usr/share/fonts/TTF/FreeMono.ttf
#font=verdana.ttf
encoding=koi8-r
fontsize=24
symbolssize=35
blur=2
outline=1.5

make || exit

./subfont $unicode --blur $blur --outline $outline "$encoding" $fontsize "$font" || exit
./subfont --append --blur $blur --outline $outline encodings/osd-mplayer $symbolssize osd/osd.pfb || exit

#cp font.desc *.raw ~/.mplayer/font/

exit

# display *.raw files
SIZE=`awk '/bitmap size:/ {print $NF; exit}' font.desc`+800
display -size $SIZE gray:$encoding-a.raw &
display -size $SIZE gray:$encoding-b.raw &
#convert -size $SIZE gray:$encoding-a.raw $encoding-a.png
#convert -size $SIZE gray:$encoding-b.raw $encoding-b.png
