#include "../../mplayerxp/mm_accel.h"

#define MPEG2_ACCEL_X86_MMX	MM_ACCEL_X86_MMX
#define MPEG2_ACCEL_X86_3DNOW	MM_ACCEL_X86_3DNOW
#define MPEG2_ACCEL_X86_MMXEXT	MM_ACCEL_X86_MMXEXT

#define MPEG2_ACCEL_PPC_ALTIVEC 1
#define MPEG2_ACCEL_ALPHA 1
#define MPEG2_ACCEL_ALPHA_MVI 2
#define MPEG2_ACCEL_SPARC_VIS 1
#define MPEG2_ACCEL_SPARC_VIS2 2
