/*  KEY code definitions for GyS-TermIO v2.0  (C) 1999 A'rpi/ESP-team */
#ifndef KEYCODES_H_INCLUDED
#define KEYCODES_H_INCLUDED 1
namespace mpxp {
    enum {
	KEY_ENTER		=13,
	KEY_TAB			=9,

	KEY_BASE		=0x100,
/*  Function keys  */
	KEY_F			=(KEY_BASE+64),
/* Control keys */
	KEY_CTRL		=(KEY_BASE),
	KEY_BACKSPACE		=(KEY_CTRL+0),
	KEY_DELETE		=(KEY_CTRL+1),
	KEY_INSERT		=(KEY_CTRL+2),
	KEY_HOME		=(KEY_CTRL+3),
	KEY_END			=(KEY_CTRL+4),
	KEY_PAGE_UP		=(KEY_CTRL+5),
	KEY_PAGE_DOWN		=(KEY_CTRL+6),
	KEY_ESC			=(KEY_CTRL+7),
/* Control keys short name */
	KEY_BS			=KEY_BACKSPACE,
	KEY_DEL			=KEY_DELETE,
	KEY_INS			=KEY_INSERT,
	KEY_PGUP		=KEY_PAGE_UP,
	KEY_PGDOWN		=KEY_PAGE_DOWN,
	KEY_PGDWN		=KEY_PAGE_DOWN,
/* Cursor movement */
	KEY_CRSR		=(KEY_BASE+16),
	KEY_RIGHT		=(KEY_CRSR+0),
	KEY_LEFT		=(KEY_CRSR+1),
	KEY_DOWN		=(KEY_CRSR+2),
	KEY_UP			=(KEY_CRSR+3),
/* XF86 Multimedia keyboard keys */
	KEY_XF86_BASE		=(0x100+384),
	KEY_XF86_POWER		=(KEY_XF86_BASE+0),
	KEY_XF86_PAUSE		=(KEY_XF86_BASE+1),
	KEY_XF86_STOP		=(KEY_XF86_BASE+2),
	KEY_XF86_PREV		=(KEY_XF86_BASE+3),
	KEY_XF86_NEXT		=(KEY_XF86_BASE+4),
	KEY_XF86_VOLUME_UP	=(KEY_XF86_BASE+5),
	KEY_XF86_VOLUME_DN	=(KEY_XF86_BASE+6),
	KEY_XF86_MUTE		=(KEY_XF86_BASE+7),
	KEY_XF86_EJECT		=(KEY_XF86_BASE+8),
	KEY_XF86_MENU		=(KEY_XF86_BASE+9),
	KEY_XF86_PLAY		=(KEY_XF86_BASE+10),
	KEY_XF86_FORWARD	=(KEY_XF86_BASE+12),
	KEY_XF86_REWIND		=(KEY_XF86_BASE+13),
	KEY_XF86_STANDBY	=(KEY_XF86_BASE+14),
	KEY_XF86_BRIGHTNESS	=(KEY_XF86_BASE+15),
	KEY_XF86_CONTRAST	=(KEY_XF86_BASE+16),
	KEY_XF86_SATURATION	=(KEY_XF86_BASE+17),
	KEY_XF86_SCREENSAVE	=(KEY_XF86_BASE+18),
	KEY_XF86_REFRESH	=(KEY_XF86_BASE+19),
/* Keypad keys */
	KEY_KEYPAD		=(KEY_BASE+32),
	KEY_KP0			=(KEY_KEYPAD+0),
	KEY_KP1			=(KEY_KEYPAD+1),
	KEY_KP2			=(KEY_KEYPAD+2),
	KEY_KP3			=(KEY_KEYPAD+3),
	KEY_KP4			=(KEY_KEYPAD+4),
	KEY_KP5			=(KEY_KEYPAD+5),
	KEY_KP6			=(KEY_KEYPAD+6),
	KEY_KP7			=(KEY_KEYPAD+7),
	KEY_KP8			=(KEY_KEYPAD+8),
	KEY_KP9			=(KEY_KEYPAD+9),
	KEY_KPDEC		=(KEY_KEYPAD+10),
	KEY_KPINS		=(KEY_KEYPAD+11),
	KEY_KPDEL		=(KEY_KEYPAD+12),
	KEY_KPENTER		=(KEY_KEYPAD+13)
    };
} // namespace mpxp
#endif
