/*
 * This file declares additional functions generated by mmx2c utility.
 * Fixes fome lacks of intrinsic technology.
 *
 * An intrinsic is a function known by the compiler that directly maps to a sequence of one or more assembly
 * language instructions.
*/
#ifndef __MMX2C_H_INCLUDED
#define __MMX2C_H_INCLUDED 1

static __inline __m64 __attribute__((__gnu_inline__, __always_inline__))
_m_load(void const *__P)
{
    return *(__m64 const *)__P;
}

static __inline __m64 __attribute__((__gnu_inline__, __always_inline__))
_m_load_half(void const *__P)
{
    __m64 ret;
    asm ("movd %1, %0":"=y"(ret):"m"(*(char const *)__P));
    return ret;

}

static __inline void __attribute__((__gnu_inline__, __always_inline__))
_m_store(void *__P, __m64 src)
{
    *(__m64 *)__P = src;
}

static __inline void __attribute__((__gnu_inline__, __always_inline__))
_m_store_half(void *__P, __m64 src)
{
    asm ("movd %1, %0":"=m"(*(char *)__P):"y"(src));
}
#endif
